controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

oauth_check:
    path: /oauth/check/{service}
    controller: App\Controller\SecurityController::check
